name: Run Tests
on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    name: Install and test
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci;
