name: Wait and Check
on:
  pull_request:
    branches:
      - main

jobs:
  wait-and-check:
    name: Wait and Check
    runs-on: ubuntu-latest

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ref: ${{ github.event.pull_request.head.sha }}
          check-name: install-and-test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: wait-and-check
          wait-interval: 10

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci;
